enforce_dependencies: true
# enforce_privacy: true # Removed as it might be an unsupported key or misconfiguration
# metadata:
#   owner: YourTeam # Optional: Specify team ownership
dependencies:
  - . # Depends on the root package where core models/commands are assumed to be.
