# frozen_string_literal: true

require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe '/chromosomes/:chromosome_id/alleles' do
  let(:chromosome) { FactoryBot.create(:chromosome) }

  let(:valid_attributes) do
    { name: 'legs', type: 'Integer', minimum: 1, maximum: 50 }
  end

  let(:invalid_attributes) do
    { name: 'legs', type: 'Integer' }
  end

  describe 'GET /index' do
    it 'renders a successful response' do
      chromosome.alleles << Allele.new_with_integer(name: 'legs', minimum: 1, maximum: 50)
      get chromosome_alleles_url(chromosome)
      expect(response).to be_successful
    end
  end

  describe 'GET /show' do
    it 'renders a successful response' do
      allele = (chromosome.alleles << Allele.new_with_integer(name: 'legs', minimum: 1, maximum: 50)).last
      get chromosome_allele_url(chromosome, allele)
      expect(response).to be_successful
    end
  end

  describe 'POST /create' do
    context 'with valid parameters' do
      it 'creates a new Allele' do
        expect do
          post chromosome_alleles_url(chromosome), params: { allele: valid_attributes }
        end.to change(Allele, :count).by(1)
      end

      it 'returns a 201 response' do
        post chromosome_alleles_url(chromosome), params: { allele: valid_attributes }
        expect(response).to have_http_status(:created)
      end
    end

    context 'with invalid parameters' do
      it 'does not create a new Allele' do
        expect do
          post chromosome_alleles_url(chromosome), params: { allele: invalid_attributes }
        end.not_to change(Allele, :count)
      end

      it 'returns 422' do
        post chromosome_alleles_url(chromosome), params: { allele: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_content)
      end
    end
  end

  describe 'PATCH /update' do
    let(:allele) { (chromosome.alleles << Allele.new_with_integer(name: 'legs', minimum: 1, maximum: 50)).last }

    context 'with valid parameters' do
      it 'updates the requested allele' do
        patch chromosome_allele_url(chromosome, allele), params: { allele: { minimum: 2, maximum: 60 } }
        expect(response).to have_http_status(:ok)
        expect(allele.reload.inheritable.minimum).to eq(2)
        expect(allele.reload.inheritable.maximum).to eq(60)
      end
    end

    context 'with invalid parameters' do
      it 'rejects changing type' do
        patch chromosome_allele_url(chromosome, allele), params: { allele: { type: 'Float' } }
        expect(response).to have_http_status(:unprocessable_content)
      end
    end
  end

  describe 'DELETE /destroy' do
    it 'destroys the requested allele' do
      allele = (chromosome.alleles << Allele.new_with_integer(name: 'legs', minimum: 1, maximum: 50)).last
      expect do
        delete chromosome_allele_url(chromosome, allele)
      end.to change(Allele, :count).by(-1)
    end

    it 'returns 204' do
      allele = (chromosome.alleles << Allele.new_with_integer(name: 'legs', minimum: 1, maximum: 50)).last
      delete chromosome_allele_url(chromosome, allele)
      expect(response).to have_http_status(:no_content)
    end
  end
end
